# Generated by Django 6.0 on 2025-12-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_color_primario_marca_color_coorporativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0, help_text='1 sale primero, 2 después ...')),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.marca')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='InsumoCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pescado, Limón, Gas', max_length=50)),
                ('disponible', models.BooleanField(default=True, help_text='Desmarcar para apagar todos los platos relacionados')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción para la web')),
                ('activo_manual', models.BooleanField(default=True, help_text='Apagar este plato manualmente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='catalogo.categoria')),
                ('insumos_clave', models.ManyToManyField(blank=True, to='catalogo.insumocritico')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='core.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Estándar', help_text='Ej: Personal, Fuente, Vaso', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.plato')),
            ],
        ),
    ]
