# Generated by Django 6.0 on 2025-12-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar si se agotó solo esta presentación', verbose_name='¿Disponible?'),
        ),
    ]
