# Generated by Django 6.0 on 2025-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_variante_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_singular',
            field=models.CharField(blank=True, help_text="Ej: 'Chicharron' (para que salga 'Chicharron de Pollo')", max_length=50, null=True),
        ),
    ]
