# Generated by Django 6.0 on 2025-12-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_nombre_singular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='plato',
            name='orden',
            field=models.IntegerField(default=0, help_text='1 sale primero, 2 después...'),
        ),
    ]
