# Generated by Django 5.1.7 on 2025-12-14 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_plato_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_seleccion_multiple', models.BooleanField(default=False, verbose_name='¿Permitir varios?')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='¿Es obligatorio?')),
                ('minimo', models.IntegerField(default=0, help_text='Mínimo de opciones a elegir')),
                ('maximo', models.IntegerField(default=1, help_text='Máximo de opciones a elegir (si es múltiple)')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='opciones',
            field=models.ManyToManyField(blank=True, related_name='platos', to='catalogo.grupoopciones', verbose_name='Personalización'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.grupoopciones')),
            ],
        ),
    ]
