# Generated by Django 5.1.7 on 2025-12-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_grupoopciones_plato_opciones_opcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='opciones',
        ),
        migrations.AddField(
            model_name='variante',
            name='opciones',
            field=models.ManyToManyField(blank=True, to='catalogo.grupoopciones', verbose_name='Grupos de Opciones'),
        ),
    ]
