# Generated by Django 5.1.7 on 2025-12-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_remove_plato_opciones_variante_opciones'),
        ('pedidos', '0003_remove_detallepedido_opciones_elegidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='opciones',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='GrupoOpciones',
        ),
    ]
