# Generated by Django 5.1.7 on 2025-12-15 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_variante_opciones_delete_opcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo (Ej: Guarniciones)')),
                ('seleccion_multiple', models.BooleanField(default=False, help_text='Check = Checkboxes (Varios). Sin check = Radio Buttons (Solo uno).', verbose_name='¿Permitir varios?')),
                ('obligatorio', models.BooleanField(default=False, help_text='El cliente NO podrá agregar al carrito sin elegir esto.', verbose_name='¿Es obligatorio?')),
                ('minimo', models.PositiveIntegerField(default=0, verbose_name='Mínimo a elegir')),
                ('maximo', models.PositiveIntegerField(default=1, verbose_name='Máximo a elegir')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Opciones',
                'verbose_name_plural': 'Grupos de Opciones',
            },
        ),
        migrations.AddField(
            model_name='variante',
            name='grupos_opciones',
            field=models.ManyToManyField(blank=True, to='catalogo.grupoopciones', verbose_name='Personalización disponible'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo adicional (0.00 si es gratis)', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.grupoopciones')),
            ],
        ),
    ]
