# Generated by Django 5.1.7 on 2025-12-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_grupoopciones_variante_grupos_opciones_opcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cubiertos, Salsas, Servilletas', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inclusión',
                'verbose_name_plural': 'Inclusiones',
            },
        ),
        migrations.AddField(
            model_name='variante',
            name='inclusiones',
            field=models.ManyToManyField(blank=True, to='catalogo.inclusion', verbose_name='Elementos incluidos de fábrica'),
        ),
    ]
