# Generated by Django 6.0 on 2025-12-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Identificador para URL (Ej: terramar)', unique=True)),
                ('color_primario', models.CharField(default='#003366', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('estado_actual', models.CharField(choices=[('NORMAL', 'Operacion Normal'), ('SATURADO', 'Alta Demanda (+Tiempo)'), ('PAUSA', 'Pausa (No recibir pedidos)'), ('CERRADO', 'Cierre Total')], default='NORMAL', max_length=20)),
                ('tiempo_delivery_base', models.IntegerField(default=30, help_text='Tiempo base promedio en esta zona')),
                ('tiempo_extra_saturacion', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField(default=4)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('PAGANDO', 'Pagando')], default='LIBRE', max_length=20)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='core.sede')),
            ],
        ),
    ]
