# Generated by Django 6.0 on 2025-12-10 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='color_primario',
            new_name='color_coorporativo',
        ),
        migrations.AddField(
            model_name='mesa',
            name='qr_hash',
            field=models.CharField(blank=True, help_text='Código único para el QR', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('puntos_acumulados', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nivel', models.CharField(choices=[('BRONCE', '🥉 Nuevo'), ('PLATA', '🥈 Frecuente'), ('ORO', '🥇 VIP')], default='BRONCE', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tema Verano 2025', max_length=50)),
                ('activo', models.BooleanField(default=False, help_text='Al activar este, se desactivan los demás automáticamente')),
                ('color_principal', models.CharField(default='#003366', help_text='Barra superior y botones principales', max_length=7)),
                ('color_secundario', models.CharField(default='#FF6B4A', help_text='Ofertas y botones de acción', max_length=7)),
                ('color_fondo', models.CharField(default='#F4F7F6', help_text='Fondo de la página', max_length=7)),
                ('mensaje_barra', models.CharField(default='Bienvenido', help_text='Texto arriba del todo', max_length=200)),
                ('mensaje_despedida', models.CharField(default='¡Gracias por tu compra!', help_text='Mensaje al finalizar', max_length=200)),
                ('efecto_especial', models.CharField(choices=[('NINGUNO', 'Sin efectos (Limpio)'), ('NIEVE', '❄️ Caída de Nieve (Navidad)'), ('CONFETI', '🎉 Lluvia de Confeti (Aniversario)'), ('OSCURO', '🌙 Modo Oscuro (Elegante)'), ('PERU', '🇵🇪 Modo Patrio')], default='NINGUNO', max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='core.marca')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_GLOBAL', '👑 Super Admin (Dueño)'), ('ADMIN_SEDE', '👔 Gerente de Local'), ('CAJERO', '💻 Cajero'), ('COCINA', '🍳 Chef / Cocina'), ('MOZO', '📝 Mesero')], default='MOZO', max_length=20)),
                ('pin_acceso', models.CharField(blank=True, help_text='PIN para Tablet', max_length=4, null=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sede')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
