# Generated by Django 6.0 on 2025-12-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0002_rename_color_primario_marca_color_coorporativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_contacto', models.CharField(default='Invitado', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('tipo_servicio', models.CharField(choices=[('MESA', 'Mesa'), ('DELIVERY', 'Delivery'), ('RECOJO', 'Para Llevar')], default='MESA', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', '🟡 Pendiente'), ('CONFIRMADO', '🟠 En Cocina'), ('LISTO', '🔵 Listo para Servir'), ('ENTREGADO', '🟢 Finalizado'), ('CANCELADO', '🔴 Anulado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mesa')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.sede')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.CharField(blank=True, help_text='Ej: Sin picante', max_length=200)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.variante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
        ),
    ]
