# Generated by Django 5.1.7 on 2025-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_grupoopciones_plato_opciones_opcion'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='opciones_elegidas',
            field=models.ManyToManyField(blank=True, to='catalogo.opcion'),
        ),
    ]
