# Generated by Django 5.1.7 on 2025-12-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido_opciones_elegidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='opciones_elegidas',
        ),
    ]
