"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
env = environ.Env()
env_file = BASE_DIR / '.env'

if env_file.exists():
    environ.Env.read_env(str(env_file))
else:
    print(f"⚠️  ALERTA: No encuentro el archivo en: {env_file}")
    print("⚠️  Verifica que el archivo se llame '.env' y no '.env.txt'")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-clave-de-respaldo-para-desarrollo')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default = False)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    #'unfold', #tema blanco
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Mis Archivos Terramar
    'core',
    'catalogo',
    'pedidos',
    'dashboard',
    'admin_reorder',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.informacion_marca',
                'pedidos.context_processors.carrito_actual',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# URL pública (lo que escribe el navegador)
MEDIA_URL = '/media/'

# Ruta física (dónde se guardan en tu PC)
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CONFIGURACIÓN DE JAZZMIN (ADMIN PANEL) ---

JAZZMIN_SETTINGS = {
    # Usamos default=... para que si falta el .env, no explote
    "site_title": env('ADMIN_HEADER', default='Terramar Admin'),
    "site_header": env('PROJECT_NAME', default='Terramar ERP'),
    "site_brand": env('PROJECT_NAME', default='Terramar ERP'),
    "welcome_sign": f"Bienvenido a {env('PROJECT_NAME', default='Terramar')}",
    "copyright": "Terramar Ltd",
    "search_model": "core.Cliente", # Nota: Funcionará cuando crees el modelo Cliente
    
    # Menú lateral
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # --- ACTIVAR EL CONSTRUCTOR VISUAL (UI BUILDER) ---
    "show_ui_builder": True, 
    
    # Iconos para tus apps (FontAwesome)
    "icons": {
        # Identidad
        "core.Marca": "fas fa-store",
        "core.ConfiguracionVisual": "fas fa-paint-brush",
        
        # Sedes
        "core.Sede": "fas fa-map-marker-alt",
        "core.Mesa": "fas fa-chair",
        "catalogo.InsumoCritico": "fas fa-exclamation-triangle",
        
        # Carta
        "catalogo.Categoria": "fas fa-list",
        "catalogo.Plato": "fas fa-utensils",
        
        # Personas
        "core.PerfilEmpleado": "fas fa-user-tie",
        "core.Cliente": "fas fa-users",
        "auth.User": "fas fa-key",

        # Pedidos
        "pedidos.Pedido": "fas fa-cash-register",
    },
}

# --- AJUSTES VISUALES (Aquí se guardarán tus colores) ---
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly", # <--- AQUÍ PUEDES CAMBIAR EL TEMA (Ej: darkly, journal, solar)
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# --- ORDENAMIENTO DEL PANEL (ADMIN REORDER) ---

ADMIN_REORDER = (
    # GRUPO 1: Identidad Corporativa (Lo que toca el dueño estratégico)
    {
        'app': 'core', 
        'label': '🏢 Identidad y Marketing', 
        'models': (
            'core.Marca', 
            'core.ConfiguracionVisual',  # Temas Navidad/Verano
        )
    },
    
    # GRUPO 2: Gestión de Locales (Lo físico)
    {
        'app': 'core', 
        'label': '📍 Gestión de Sedes', 
        'models': (
            'core.Sede',
            'core.Mesa',
            'catalogo.InsumoCritico', # El "Kill Switch" va aquí porque es operativo
        )
    },

    # GRUPO 3: El Menú (Lo que se vende)
    {
        'app': 'catalogo', 
        'label': '🍔 Carta Digital', 
        'models': (
            'catalogo.Categoria',
            'catalogo.Plato',
            # Nota: Variante está dentro de Plato, así que no necesitamos listarla aquí
        )
    },

    # GRUPO 4: Personas (Usuarios)
    {
        'app': 'core', 
        'label': '👥 Usuarios y Clientes', 
        'models': (
            'core.PerfilEmpleado', # Tus empleados
            'core.Cliente',        # Tus clientes fidelizados
            'auth.User',           # Usuarios del sistema (Login)
            # 'auth.Group',        # Grupos (Opcional, si no lo usas, coméntalo)
        )
    },
    
    # GRUPO 5: Administración Técnica (Opcional, para ti)
    # Si tienes otras apps como 'pedidos', agrégalas en otro grupo cuando las crees.

    {
        'app': 'pedidos', 
        'label': '💰 Gestión de Ventas', 
        'models': (
            'pedidos.Pedido',
            # 'pedidos.DetallePedido', # Opcional: Descomenta si quieres ver los platos sueltos
        )
    },

)


CART_SESSION_ID = 'carrito' 
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')